.PHONY: clean All

All:
	@echo "----------Building project:[ alarmsystem - Debug ]----------"
	@cd "alarmsystem" && "$(MAKE)" -f  "alarmsystem.mk" && "$(MAKE)" -f  "alarmsystem.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ alarmsystem - Debug ]----------"
	@cd "alarmsystem" && "$(MAKE)" -f  "alarmsystem.mk" clean
